#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include "card.h"
#include "dealer.h"
#include "deck.h"
#include "engine.h"
#include "hand.h"
#include "input.h"

// Currently generated by an LLM, will fix later
Deck simulate_hand(
    Hand player_hand,
    Hand dealer_hand,
    Deck deck,
    int can_play,
    int can_double,
    int can_split,
    float bj_payout,
    int sur_allowed,
    int s17,
    int das,
    int rsa,
    int psa,
    int remaining_splits,
    int double_restrictions[DOUBLE_RESTRICTION_COUNT],
    int dealer_peeks
) {
    MoveEV move_ev = any_hand_ev(
        player_hand,
        dealer_hand,
        deck,
        can_play,
        can_double,
        can_split,
        bj_payout,
        sur_allowed,
        s17,
        das,
        rsa,
        psa,
        remaining_splits,
        double_restrictions,
        dealer_peeks
    );

    printf("Recommended move: %i (EV %.4f)\n", move_ev.move, move_ev.ev);
    printf("Move (0=Stand,1=Hit,2=Double,3=Surrender,4=Split): ");

    int move;
    scanf("%d", &move);

    if (move == STAND) {
        while (should_dealer_hit(dealer_hand, s17)) {
            printf("Dealer drew: ");
            Card card = get_card_input();
            dealer_hand = append_card(dealer_hand, card);
            deck = remove_card(deck, card);
        }
    }
    else if (move == HIT) {
        printf("Player drew: ");
        Card card = get_card_input();

        player_hand = append_card(player_hand, card);
        deck = remove_card(deck, card);

        deck = simulate_hand(
            player_hand,
            dealer_hand,
            deck,
            1,
            0,
            0,
            bj_payout,
            sur_allowed,
            s17,
            das,
            rsa,
            psa,
            remaining_splits,
            double_restrictions,
            dealer_peeks
        );
    }
    else if (move == DOUBLE) {
        printf("Player drew: ");
        Card card = get_card_input();

        player_hand = append_card(player_hand, card);
        deck = remove_card(deck, card);

        while (should_dealer_hit(dealer_hand, s17)) {
            printf("Dealer drew: ");
            card = get_card_input();
            dealer_hand = append_card(dealer_hand, card);
            deck = remove_card(deck, card);
        }
    }
    else if (move == SURRENDER) {
        return deck;
    }
    else if (move == SPLIT) {
        /*
         Construct the two split hands here using your existing
         append_card()/remove_card() helpers.

         Then:

         deck = simulate_hand(left_hand, ...);
         deck = simulate_hand(right_hand, ...);
        */
    }

    return deck;
}


int main(int argc, char *argv[]) {
    printf("Welcome to Luke's Blackjack Engine");

    // Set defaults
    int num_decks = 8;
    float bj_payout = 1.5;
    int sur_allowed = 0;
    int s17 = 0;
    int das = 1;
    int rsa = 0;
    int psa = 1;
    int max_splits = 4;
    int double_restrictions[DOUBLE_RESTRICTION_COUNT] = {0};
    int dealer_peeks = 1;

    // Parser
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-d") == 0 && i + 1 < argc) {
            num_decks = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-p") == 0 && i + 1 < argc) {
            bj_payout = atof(argv[++i]);
        }
        else if (strcmp(argv[i], "-s") == 0 && i + 1 < argc) {
            sur_allowed = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-s17") == 0 && i + 1 < argc) {
            s17 = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-das") == 0 && i + 1 < argc) {
            das = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-rsa") == 0 && i + 1 < argc) {
            rsa = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-psa") == 0 && i + 1 < argc) {
            psa = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-ms") == 0 && i + 1 < argc) {
            max_splits = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-dp") == 0 && i + 1 < argc) {
            dealer_peeks = atoi(argv[++i]);
        }
        else if (strcmp(argv[i], "-dr") == 0) {
            while (i + 1 < argc && argv[i + 1][0] != '-') {
                int total = atoi(argv[++i]);

                if (total >= 1 && total < DOUBLE_RESTRICTION_COUNT) {
                    double_restrictions[total] = 1;
                }
            }
        }
    }

    Deck deck = generate_deck(num_decks);

    while (1) {
        printf("Enter your first card: ");
        Card player_card0 = get_card_input();
        deck = remove_card(deck, player_card0);

        printf("Enter your second card: ");
        Card player_card1 = get_card_input();
        deck = remove_card(deck, player_card1);

        printf("Enter your first card: ");
        Card dealer_upcard = get_card_input();
        deck = remove_card(deck, dealer_upcard);

        Hand player_hand = {0};
        player_hand = append_card(player_hand, player_card0);
        player_hand = append_card(player_hand, player_card1);

        Hand dealer_hand = {0};
        dealer_hand = append_card(dealer_hand, dealer_upcard);

        if (dealer_peeks && (dealer_upcard == ACE || dealer_upcard == TEN)) {
            printf("Does the dealer have a blackjack: ");
            char answer = getchar();

            if (answer == 'y' || answer == 'Y') {
                if (dealer_upcard == ACE) {
                    deck = remove_card(deck, TEN);
                } else {
                    deck = remove_card(deck, ACE);
                }
                continue;
            }
        }

        simulate_hand(player_hand, dealer_hand, deck,
            1, 1, is_pair(player_hand) && max_splits > 0,
            bj_payout, sur_allowed, s17, das, rsa, psa, max_splits, double_restrictions, dealer_peeks
        );
    }
}
